# Taps
tap "caskroom/cask"
tap "caskroom/eid"
tap "caskroom/fonts"
tap "caskroom/versions"
tap "homebrew/bundle"

# Cask Dependencies
brew "mas"
brew "pkg-config"
cask "java"

# Shells
brew "bash"
brew "zsh"
brew "zsh-completions"

# CLI Utilities
brew "coreutils"
brew "curl", args: ["with-nghttp2"]
brew "git"
brew "grep"
brew "tree"
brew "wget"

# macOS Tools
brew "mackup"
brew "trash"

# Other Tools
brew "imagemagick"
brew "libyaml"

# Development
brew "composer"
brew "go"
brew "php"
brew "pyenv"
brew "node"
brew "yarn"

# Apps
cask "1password"
cask "adobe-acrobat-reader"
cask "adobe-creative-cloud"
cask "discord"
cask "docker"
cask "dropbox"
cask "droplr"
cask "eid-pt"
cask "google-cloud-sdk"
cask "iterm2"
cask "microsoft-office"
cask "now"
cask "postbox"
cask "postman"
cask "sequel-pro"
cask "skype"
cask "slack"
cask "spotify"
cask "tableplus"
cask "there"
cask "tower"
cask "visual-studio-code"

# Screensavers
cask "aerial"

# Browsers
cask "firefox"
cask "google-chrome"

# Quicklook
cask "qlcolorcode"
cask "qlmarkdown"
cask "qlstephen"
cask "quicklook-json"
cask "quicklook-csv"

# Fonts
cask "font-fira-code"
cask "font-source-code-pro-for-powerline"
cask "font-source-code-pro"
cask "font-source-sans-pro"
cask "font-source-serif-pro"

# MAS Applications
mas "Bear", id: 1091189122
mas "Clocker", id: 1056643111
mas "Trello", id: 1278508951
mas "Todoist", id: 585829637
